
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

  
development:
  <<: *default
  database: project3_development

test:
  <<: *default
  database: project3_test


production:
  <<: *default
  database: project3_production
  #username: flixter
  #password: <%= ENV['FLIXTER_DATABASE_PASSWORD'] %>
